bot: ConciseBot  # Current choices: ConciseBot, RickBot
model: GPT-4o  # Current choices: MockModel, GPT-3.5, GPT-4, GPT-4o
history: chat01
history_size: 25
dirs:
  bots: bots/
  history: history/
  saved: saved/
files:
  env: .env
avatars:
  user: 👤
  bot: 🤖
