bot: default
model: mock
history: chat01
history_size: 25
save_config_on_exit: true
save_history_on_exit: false
dirs:
  bots: bots/
  history: history/
  saved: saved/
files:
  env: .env
style:
  user: ''
  bot: '#00ADB2'
  error: ansired
