bot: ConciseBot  # Current choices: ConciseBot, RickBot
model: gpt-4o  # e.g., gpt-3.5-turbo, gpt-4-turbo, gpt-4o, mock-model
history_size: 25
paths:
  # Paths can be specified as either absolute or relative:
  # - Absolute paths: These start with a "/" and represent the full path from the root directory of the filesystem.
  # - Relative paths: These do not start with a "/" and are interpreted relative to the location of this config.yaml file.
  # For example, to access the "bots" directory inside the "ask" directory, you can use the relative path "../ask/bots/"
  bots: bots/
avatars:
  user: 👤
  bot: 🤖
