bot: ConciseBot  # Current choices: ConciseBot, RickBot
model: gpt-4o  # e.g., gpt-3.5-turbo, gpt-4-turbo, gpt-4o, mock-model
history_size: 25
paths:
  # Paths that start with "/" are absolute
  # If a path doesn't start with "/", then it is relative to this config.yaml file
  # You can e.g., access the bots of the ask directory by changing the relative path to "../ask/bots/"
  bots: bots/
avatars:
  user: 👤
  bot: 🤖
