bot: AskBot  # Current choices: AskBot
model: gpt-4o  # e.g., gpt-3.5-turbo, gpt-4-turbo, gpt-4o, mock-model
history_size: 1
paths:  
  # Paths can be specified as either absolute or relative:
  # - Absolute: Paths that start with "/" (or a drive letter and ":\\" on windows) and represent the full path from the root directory of the filesystem.
  # - Relative: Do not start with "/" and are relative to the location of this config file.
  bots: bots/
